### ISSUE TITLE
Initial subscription limited to 50 groups

### ISSUE THREAD

**Issue by kichik** [aws-samples/amazon-cloudwatch-log-centralizer#1]
The following function uses `describe_log_groups()` but ignores `nextToken`. By default `limit` is set to `50` so that means no more than 50 log groups will be subscribed.

https://github.com/aws-samples/amazon-cloudwatch-log-centralizer/blob/6b69a1da34036761c5ce4bcd49853e202973a03c/python/CentralLogging.py#L13-L16

CloudTrail events will catch new log groups, but existing groups will remain unsubscribed.

**Comment by davidlbailey11** [comment]
Good catch, thanks.  Updated the code to include the nextToken.
