### ISSUE TITLE
Placeholders replaced with 612487a

### ISSUE THREAD

**Issue by leonblueconic** [aws-samples/amazon-cloudwatch-log-centralizer#2]
With commit 612487a a number of placeholders in cfn/centralLogging.yml have been replaced by actual account numbers.  This is noticeable in line 112.  As the placeholders are referenced in https://aws.amazon.com/blogs/architecture/stream-amazon-cloudwatch-logs-to-a-centralized-account-for-audit-and-analysis/ this now makes it harder to follow the those instructions.

**Comment by davidlbailey11** [comment]
Thanks for letting me know.  I returned the missing placeholders.
