### ISSUE TITLE
log extension

### ISSUE THREAD

**Issue by nenads** [aws-samples/amazon-cloudwatch-log-centralizer#3]
Is there easy way to add file extension like .gz so Amazone Athena can read logs ?

**Comment by davidlbailey11** [comment]
Logs flowing through subscription filters to Kinesis FireHose or Lambdas are already zipped.  I would recommend looking at examples of reading CloudWatch Logs with Athena, such as this: https://www.transposit.com/blog/2019.12.13-querying-cloudwatch-logs-with-athena/
